# Generated by Django 5.2 on 2026-08-19 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("bio", models.TextField(blank=True)),
                ("country", models.CharField(blank=True, max_length=50)),
                ("formed_date", models.DateField(blank=True, null=True)),
                ("is_band", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("members", models.ManyToManyField(blank=True, to="music.artist")),
            ],
        ),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="albums/"),
                ),
                ("description", models.TextField(blank=True)),
                ("release_date", models.DateField()),
                (
                    "album_type",
                    models.CharField(
                        choices=[
                            ("LP", "LP"),
                            ("EP", "EP"),
                            ("SINGLE", "Single"),
                            ("COMPILATION", "Compilation"),
                        ],
                        default="SINGLE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="music.artist",
                    ),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        blank=True, related_name="albums", to="music.genre"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("duration", models.DurationField(blank=True, null=True)),
                ("track_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "audio_file",
                    models.FileField(blank=True, null=True, upload_to="songs/"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="songs/covers/"),
                ),
                ("release_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="music.album",
                    ),
                ),
                (
                    "artists",
                    models.ManyToManyField(related_name="songs", to="music.artist"),
                ),
                (
                    "genre",
                    models.ManyToManyField(
                        blank=True, related_name="songs", to="music.genre"
                    ),
                ),
            ],
        ),
    ]
